### ISSUE TITLE
Cool but it‘s doesn‘t work for me

### ISSUE THREAD

**Issue by Fabbboy** [xTobyPlayZ/KahootFlooder#2]
Im using Replit, because i have a school Ipad and no Python IDE and there it‘s didnt work

Is there any other ways?

**Comment by Fabbboy** [comment]
There is a error on line 65

**Comment by xTobyPlayZ** [comment]
Hi there, this project requires the Selenium web driver to work which isn't available for iOS. Also, this project has been abandoned as I have moved development to my new Kahoot Flood website: https://kahootflood.games - This will work on all devices as it is browser based. Thanks!

**Comment by xTobyPlayZ** [comment]
Hi there, this project requires the Selenium web driver to work which isn't available for iOS. Also, this project has been abandoned as I have moved development to my new Kahoot Flood website: https://kahootflood.games - This will work on all devices as it is browser based (although not yet optimized for mobile, but it still works) Thanks!
